#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

wget --no-check-certificate https://abinit.github.io/abinit_web/ATOMICDATA/LDA_FHI.zip
unzip LDA_FHI.zip
cp LDA_FHI/14-Si.LDA.fhi .
