#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "band.dat",
]

# difference of eigen energies for io=1 and io=2 with ik=2"
reference_value_1 = 0.072123
permissible_error_1 = 0.00004 # (~0.001eV)

# difference of eigen energies for io=16 and io=17 with ik=2"
reference_value_2 = 0.078642
permissible_error_2 = 0.00004 # (~0.001eV)

# difference of eigen energies for io=1 and io=2 with ik=1"
reference_value_3 = 0.154004
permissible_error_3 = 0.00004 # (~0.001eV)

# difference of eigen energies for io=16 and io=17 with ik=1"
reference_value_4 = 0.020381
permissible_error_4 = 0.00004 # (~0.001eV)

print("# Checking the existance of outputfile")
for item in filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure

print("# Checking calculated result")

linecount = 0
for line in open("band.dat"):
    linecount += 1
    if linecount ==  5: # line  5 (io=1, ik=1)
       data = line.split()
       v5 = float(data[2])
    if linecount ==  6: # line  6 (io=2, ik=1)
       data = line.split()
       v6 = float(data[2])
    if linecount == 20: # line 20 (io=16, ik=1)
       data = line.split()
       v7 = float(data[2])
    if linecount == 21: # line 21 (io=17, ik=2)
       data = line.split()
       v8 = float(data[2])
    if linecount == 38: # line 38 (io=1, ik=2)
       data = line.split()
       v1 = float(data[2])
    if linecount == 39: # line 39 (io=2, ik=2)
       data = line.split()
       v2 = float(data[2])
    if linecount == 53: # line 53 (io=16, ik=2)
       data = line.split()
       v3 = float(data[2])
    if linecount == 54: # line 54 (io=17, ik=2)
       data = line.split()
       v4 = float(data[2])

diff1=v2-v1
diff2=v4-v3
diff3=v6-v5
diff4=v8-v7

if abs(diff1 - reference_value_1) > permissible_error_1:
        print("Mismatch |%e - %e| > %e)" % (diff1, reference_value_1, permissible_error_1))
        sys.exit(-1)  # Failure 

if abs(diff2 - reference_value_2) > permissible_error_2:
        print("Mismatch |%e - %e| > %e)" % (diff2, reference_value_2, permissible_error_2))
        sys.exit(-1)  # Failure 

if abs(diff3 - reference_value_3) > permissible_error_3:
        print("Mismatch |%e - %e| > %e)" % (diff3, reference_value_3, permissible_error_3))
        sys.exit(-1)  # Failure 

if abs(diff4 - reference_value_4) > permissible_error_4:
        print("Mismatch |%e - %e| > %e)" % (diff4, reference_value_4, permissible_error_4))
        sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
