#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "JM_eigen.data",
]

# difference of eigen energies for io=1 and io=2 with ik=2"
reference_value_1 = 10.55645
permissible_error_1 = 0.00004 # (~0.001eV)

# difference of eigen energies for io=5 and io=6 with ik=2"
reference_value_2 = 2.646459
permissible_error_2 = 0.00004 # (~0.001eV)

print("# Checking the existance of outputfile")
for item in filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure

print("# Checking calculated result")

linecount = 0
for line in open("JM_eigen.data"):
    linecount += 1
    if linecount == 12: # line 12 (io=1, ik=2)
       data = line.split()
       v1 = float(data[1])
    if linecount == 13: # line 13 (io=2, ik=2)
       data = line.split()
       v2 = float(data[1])
    if linecount == 16: # line 16 (io=5, ik=2)
       data = line.split()
       v3 = float(data[1])
    if linecount == 17: # line 17 (io=6, ik=2)
       data = line.split()
       v4 = float(data[1])

diff1=v2-v1
diff2=v4-v3

if abs(diff1 - reference_value_1) > permissible_error_1:
        print("Mismatch |%e - %e| > %e)" % (diff1, reference_value_1, permissible_error_1))
        sys.exit(-1)  # Failure 

if abs(diff2 - reference_value_2) > permissible_error_2:
        print("Mismatch |%e - %e| > %e)" % (diff2, reference_value_2, permissible_error_2))
        sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
