#!/bin/sh
set -eu
cp ../pseudo/H_rps.dat ./
# Read the freshly verified ordinary GS directly; no DC files are used.
test -s ../435_H_pbeh40_rvv10_conventional_gs/data_for_restart/wfn.bin
test -s ../435_H_pbeh40_rvv10_conventional_gs/data_for_restart/hybrid_gs.bin
