#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
ln -s ../204_rt_checkpoint_self/checkpoint_rt_000060 ./checkpoint_rt_000060
