#!/usr/bin/env python

# This verification script file is automatically executed after the SALMON.
# If necessary, this script file can used for the verification of the result.
# The script MUST indicate a "return-code 0", if the calculation is successful.
# If a negative value is returned, it is treated as a test failure.

import sys
import os
import re

print("#" * 60)
print("# Verification start")

filelist = [
    "Si_eigen.data",
]

restart_filelist = [
    "data_for_restart/wfn.bin",
    "data_for_restart/occupation.bin",
]

# difference of eigen energies for io = 129 and io = 128
reference_value_1 = 0.01992276
permissible_error_1 = 0.00004  # (~0.001eV)

print("# Checking the existance of outputfile")
for item in filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure

print("# Checking the existance of unfolding restart data (consumed by the RT unfold test)")
for item in restart_filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure

print("# Checking calculated result")

linecount = 0
for line in open("Si_eigen.data"):
    linecount += 1
    if linecount == 132:  #  io=128 (HOMO) at ik=1
        data = line.split()
        v1 = float(data[1])
    if linecount == 133:  #  io=129 (LUMO) at ik=1
        data = line.split()
        v2 = float(data[1])

diff1 = v2 - v1

if abs(diff1 - reference_value_1) > permissible_error_1:
    print("Mismatch |%e - %e| > %e)" % (diff1, reference_value_1, permissible_error_1))
    sys.exit(-1)  # Failure

print("# Verification end")
print("#" * 60)

sys.exit(0)  # Success
