#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
ln -s ../211_dft2tddft_distribute/data_for_restart_rt ./restart
