#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/H_rps.dat ./
cp ../pseudo/O_rps.dat ./
if [ -e H2O_info.data ]; then
  rm H2O_info.data
fi
