#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
cp ../121_bulk_Si_gs_temperature_dp/Si_gs.bin ./
if [ -e current.data ]; then
  rm current.data
fi
