#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "Si_eigen.data",
]

origin_dir = "../112_bulk_Si_rt_response_dp"
target_dir = "./"

# difference of eigen energies for io=1 and io=2 with ik=2"
reference_value_1 = 0.072123
permissible_error_1 = 0.00004

# difference of eigen energies for io=15 and io=16 with ik=2"
reference_value_2 = 0.078642
permissible_error_2 = 0.00004

print("# Checking the existance of outputfile")
for item in filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure


print("# Checking calculated result")
r = []

for line in open("Si_eigen.data"):
    r.append(line.split())

    if (len(r) <= 55):
        print("File does not have enough lines!")
        sys.exit(-1)

    v1 = float(r[37][1]) # line 38
    v2 = float(r[38][1]) # line 39
    v3 = v2-v1

    v4 = float(r[52][1]) # line 53
    v5 = float(r[53][1]) # line 54
    v6 = v5-v4

    if abs(v3 - reference_value_1) > permissible_error_1:
            print("Mismatch |%e - %e| > %e)" % (d, s, permissible_error))
            sys.exit(-1)  # Failure 

    if abs(v6 - reference_value_2) > permissible_error_2:
            print("Mismatch |%e - %e| > %e)" % (d, s, permissible_error))
            sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
