#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "Si_sbe_RT_Ac/Si_Ac_002000.data",
] 

checklist = { 
    # Ac
    "Ac": [
        -100, # Temporary value for result
        -0.00008373077038244222,  # Reference value
        3.e-5,  # Permissible error 
    ],
} 

print("# Checking the existance of outputfile") 
for item in filelist: 
    if not os.path.exists(item): 
        print("File not found: %s" % item) 
        sys.exit(-1)  # Failure 

print("# Checking calculated result")
result = {}
linecount = 0
for line in open("Si_sbe_RT_Ac/Si_Ac_004000.data"):
    linecount += 1
    if linecount == 2027: # corresponds to line 2027
        data = line.split()
        result["Ac"] = float(data[5]) # column 6
        print(result["Ac"])

for name, [resval, refval, error] in checklist.items():
    if name not in result: 
        print("Result %s (%s) is not found" % (name, ptn)) 
        sys.exit(-1)  # Failure 
    else:
        print("Result %s = %e (Reference = %e)" % (name, result[name], refval)) 
        if abs(result[name] - refval) > error: 
            print("Mismatch |%e - %e| > %e)" % (result[name], refval, error)) 
            sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
