#!/usr/bin/env python 

# This verification script file is automatically executed after the SALMON. 
# If necessary, this script file can used for the verification of the result. 
# The script MUST indicate a "return-code 0", if the calculation is successful. 
# If a negative value is returned, it is treated as a test failure. 
 
import sys 
import os 
import re 

print("#" * 60) 
print("# Verification start") 

filelist = [ 
    "Si_sbe_wave.data",
] 

checklist = {
    # 7:E_ref_z[a.u.]
    "Er": [
        -100, # Temporary value for result
        -0.371825267127976E-002,  # Reference value
        1.e-7,  # Permissible error 
    ],
    # 10:E_tra_z[a.u.]
    "Et": [
        -100, # Temporary value for result
        -0.271313839577218E-004,  # Reference value
        1.e-7,  # Permissible error 
    ],
} 

print("# Checking the existance of outputfile") 
for item in filelist: 
    if not os.path.exists(item): 
        print("File not found: %s" % item) 
        sys.exit(-1)  # Failure 

print("# Checking calculated result")
result = {}
linecount = 0
for line in open("Si_sbe_wave.data"):
    linecount += 1
    if linecount == 202: # corresponds to line 202
        data = line.split()
        result["Er"] = float(data[6]) # column 7
        print(result["Er"])
        result["Et"] = float(data[9]) # column 10
        print(result["Et"])

for name, [resval, refval, error] in checklist.items():
    if name not in result: 
        print("Result %s (%s) is not found" % (name, ptn)) 
        sys.exit(-1)  # Failure 
    else:
        print("Result %s = %e (Reference = %e)" % (name, result[name], refval)) 
        if abs(result[name] - refval) > error: 
            print("Mismatch |%e - %e| > %e)" % (result[name], refval, error)) 
            sys.exit(-1)  # Failure 

print("# Verification end") 
print("#" * 60) 

sys.exit(0)  # Success 
