#!/bin/sh
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
stress_src="$repo_root/src/common/stress.f90"
structures_src="$repo_root/src/common/structures.f90"
write_src="$repo_root/src/io/write.f90"

grep -Fq "stress_xc_dbg_grho_refresh_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_rho_box_direct_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_rho_box_direct_active_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_grho_direct_local_early_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_grho_direct_local_bulk_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_grho_local_payload_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_grho_direct_payload_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_grho_direct_local_maxdiff" "$structures_src"
grep -Fq "stress_xc_dbg_rdedd_dot_grho_local" "$structures_src"
grep -Fq "stress_xc_dbg_rdedd_dot_grho_payload" "$structures_src"
grep -Fq "stress_xc_dbg_rho_div_rdedd" "$structures_src"
grep -Fq "rho_box = 0d0" "$stress_src"
grep -Fq "rho_box(ix,iy,iz) = dble(rho_s(1)%f(ix,iy,iz))" "$stress_src"
grep -Fq "if (info%if_divide_rspace) call update_overlap_real8(srg_scalar, mg, rho_box)" "$stress_src"
grep -Fq "system%stress_xc_dbg_rho_box_direct_maxdiff = early_maxdiff_out(1)" "$stress_src"
grep -Fq "system%stress_xc_dbg_rho_box_direct_active_maxdiff = early_maxdiff_out(2)" "$stress_src"
grep -Fq "system%stress_xc_dbg_grho_direct_local_early_maxdiff = early_maxdiff_out(3)" "$stress_src"
grep -Fq "system%stress_xc_dbg_grho_direct_local_bulk_maxdiff = early_maxdiff_out(4)" "$stress_src"
grep -Fq "call calc_gradient_field(mg, stencil%coef_nab, system%rmatrix_B, rhd_direct, grho_direct)" "$stress_src"
grep -Fq "call comm_summation(diag_in, diag_out, 3, info%icomm_rko)" "$stress_src"
grep -Fq "system%stress_xc_dbg_grho_direct_payload_maxdiff = maxdiff_out(4)" "$stress_src"
grep -Fq "system%stress_xc_dbg_grho_direct_local_maxdiff = maxdiff_out(5)" "$stress_src"
grep -Fq "system%stress_xc_dbg_rdedd_dot_grho_local = diag_out(1)" "$stress_src"
grep -Fq "system%stress_xc_dbg_rdedd_dot_grho_payload = diag_out(2)" "$stress_src"
grep -Fq "system%stress_xc_dbg_rho_div_rdedd = diag_out(3)" "$stress_src"
grep -Fq "max|rho_box-rho_direct|" "$write_src"
grep -Fq "max|rho_box-rho_direct| active" "$write_src"
grep -Fq "max|grho_local_early-grho_direct|" "$write_src"
grep -Fq "max|grho_local_bulk-grho_direct|" "$write_src"
grep -Fq "max|grho_payload-grho_local|" "$write_src"
grep -Fq "max|grho_payload-grho_direct|" "$write_src"
grep -Fq "max|grho_direct-grho_local|" "$write_src"
grep -Fq "int rdedd.grho_payload + rho div(rdedd) dV" "$write_src"
