#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
ln -s ../206_gs_wf_slice/data_for_restart ./restart

