#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/C_rps.dat ./
cp ../pseudo/H_rps.dat ./
if [ -e data_for_restart/ ]; then
  rm -rf data_for_restart/
fi
if [ -e restart/ ]; then
  rm restart
fi
ln -s ../101_C2H2_gs/data_for_restart ./restart

if [ -e C2H2-RT.data ]; then
  rm C2H2-RT.data
fi


#cp ../101_C2H2_gs/C2H2_gs.bin ./
