#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/C_rps.dat ./
cp ../pseudo/H_rps.dat ./
ln -s ../185_C2H2_gs_ffte_o1/data_for_restart ./restart

