#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

cp ../pseudo/Si_rps.dat ./
if [ -e data_for_restart/ ]; then
  rm -rf data_for_restart/
fi
if [ -e restart/ ]; then
  rm restart
fi
ln -s ../111_bulk_Si_gs_dp/data_for_restart ./restart

if [ -e Si_rt.data ]; then
  rm Si_rt.data
fi


#cp ../111_bulk_Si_gs_dp/Si_gs.bin ./
