#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

wget http://www.pseudo-dojo.org/pseudos/nc-fr-04_pbe_standard/Au.upf.gz
gunzip Au.upf.gz 
ln -s ../501_bulk_Au_spin-orbit_gs/data_for_restart ./restart
