#!/usr/bin/env python

# This verification script file is automatically executed after the SALMON.
# If necessary, this script file can used for the verification of the result.
# The script MUST indicate a "return-code 0", if the calculation is successful.
# If a negative value is returned, it is treated as a test failure.

import sys
import os
import re

print("#" * 60)
print("# Verification start")

filelist = [
    "Au_eigen.data",
]

# difference of eigen energies for io=1 and io=2"
reference_value_1 = 3.688101e-01
permissible_error_1 = 4.0 # (~100eV)

# difference of eigen energies for io=15 and io=16"
reference_value_2 = 1.198156e-02
permissible_error_2 = 4.0 # (~100eV)

print("# Checking the existance of outputfile")
for item in filelist:
    if not os.path.exists(item):
        print("File not found: %s" % item)
        sys.exit(-1)  # Failure

print("# Checking calculated result")

linecount = 0
for line in open("Au_eigen.data"):
    linecount += 1
    if linecount == 4: # line 4 (io=1)
       data = line.split()
       v1 = float(data[1])
    if linecount == 5: # line 5 (io=2)
       data = line.split()
       v2 = float(data[1])
    if linecount == 18: # line 18 (io=15)
       data = line.split()
       v3 = float(data[1])
    if linecount == 19: # line 19 (io=16)
       data = line.split()
       v4 = float(data[1])

diff1=v2-v1
diff2=v4-v3

if abs(diff1 - reference_value_1) > permissible_error_1:
        print("Mismatch |%e - %e| > %e)" % (diff1, reference_value_1, permissible_error_1))
        sys.exit(-1)  # Failure

if abs(diff2 - reference_value_2) > permissible_error_2:
        print("Mismatch |%e - %e| > %e)" % (diff2, reference_value_2, permissible_error_2))
        sys.exit(-1)  # Failure

print("# Verification end")
print("#" * 60)

sys.exit(0)  # Success
