#ifndef SALMON_CONFIG_H
#define SALMON_CONFIG_H

/* #undef FORTRAN_COMPILER_HAS_MPI_VERSION3 */
#define FORTRAN_COMPILER_HAS_2MB_ALIGNED_ALLOCATION

#define SYSTEM_HAS_POSIX
#define SYSTEM_HAS_POSIX_STAT
#define SYSTEM_HAS_POSIX_ACCESS
#define SYSTEM_HAS_POSIX_MKDIR
#define SYSTEM_HAS_STDIO_REMOVE
#define SYSTEM_HAS_POSIX_NFTW

#define SYSTEM_HAS_PATH_MAX_IN_LIMITS_H
/* #undef SYSTEM_HAS_PATH_MAX_IN_LINUX_LIMITS_H */

/* #undef USE_MPI */
/* #undef USE_SCALAPACK */
/* #undef USE_EIGENEXA */
/* #undef USE_LIBXC */
/* #undef USE_FFTW */

#define USE_OPT_ARRAY_PADDING
/* #undef USE_OPT_EXPLICIT_VECTORIZATION */

#endif
