#!/bin/sh

# Test preparation script
#
# The preparation script is automatically executed before starting SALMON. 
# if required, this script file can utilized for the preparation of 
# the input data for the following calculations.

wget http://www.pseudo-dojo.org/pseudos/nc-sr_pw_standard/Si.psp8.gz
gunzip Si.psp8.gz
