#!/usr/bin/env python3
"""Plot Stage 2C Global WF+PW HHG sweep convergence metrics.

The input is the TSV/CSV summary generated by
``compare_global_wfpw_hhg_sweep.py``. The script always writes compact plotting
TSV files and writes PNG files when matplotlib is available.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


DEFAULT_METRICS = (
    "cutoff_shift_eV",
    "HHG_plateau_metric",
    "hhg_window_rms_error",
    "polarization_RMS",
    "norm_charge_drift",
)


def read_table(path: Path) -> list[dict[str, str]]:
    delimiter = "," if path.suffix.lower() == ".csv" else "\t"
    with path.open(newline="") as fp:
        rows = list(csv.DictReader(fp, delimiter=delimiter))
    if not rows:
        raise ValueError(f"{path}: empty table")
    return rows


def as_float(value: str) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def metric_columns(rows: list[dict[str, str]], requested: list[str]) -> list[str]:
    header = rows[0].keys()
    cols = [col for col in requested if col in header]
    cols.extend(col for col in header if col.startswith("H") and col.endswith("_rel_intensity_error"))
    seen = set()
    out = []
    for col in cols:
        if col not in seen:
            seen.add(col)
            out.append(col)
    return out


def filter_rows(rows: list[dict[str, str]], include_bad: bool) -> list[dict[str, str]]:
    if include_bad:
        return rows
    return [row for row in rows if row.get("bad", "F") == "F"]


def write_metric_tsv(path: Path, x_axis: str, metric: str, rows: list[dict[str, str]]) -> list[tuple[float, float]]:
    points = []
    for row in rows:
        x = as_float(row.get(x_axis, ""))
        y = as_float(row.get(metric, ""))
        if x is None or y is None:
            continue
        points.append((x, y))
    points.sort(key=lambda item: item[0])
    with path.open("w") as fp:
        fp.write(f"{x_axis}\t{metric}\n")
        for x, y in points:
            fp.write(f"{x:.16e}\t{y:.16e}\n")
    return points


def try_plot_png(path: Path, x_axis: str, metric: str, points: list[tuple[float, float]]) -> bool:
    if not points:
        return False
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except Exception:
        return False
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    fig, ax = plt.subplots(figsize=(5.0, 3.5), constrained_layout=True)
    ax.plot(xs, ys, marker="o")
    ax.set_xlabel(x_axis)
    ax.set_ylabel(metric)
    ax.grid(True, alpha=0.3)
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return True


def write_simple_svg(path: Path, x_axis: str, metric: str, points: list[tuple[float, float]]) -> bool:
    if not points:
        return False
    width, height = 640, 420
    left, right, top, bottom = 72, 24, 24, 58
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    xmin, xmax = min(xs), max(xs)
    ymin, ymax = min(ys), max(ys)
    if xmax == xmin:
        xmax = xmin + 1.0
    if ymax == ymin:
        ymax = ymin + 1.0

    def sx(x: float) -> float:
        return left + (x - xmin) / (xmax - xmin) * (width - left - right)

    def sy(y: float) -> float:
        return height - bottom - (y - ymin) / (ymax - ymin) * (height - top - bottom)

    coords = [(sx(x), sy(y)) for x, y in points]
    polyline = " ".join(f"{x:.2f},{y:.2f}" for x, y in coords)
    circles = "\n".join(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="4" fill="#1f77b4"/>' for x, y in coords)
    with path.open("w") as fp:
        fp.write(
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">\n'
            '<rect width="100%" height="100%" fill="white"/>\n'
            f'<line x1="{left}" y1="{height-bottom}" x2="{width-right}" y2="{height-bottom}" stroke="black"/>\n'
            f'<line x1="{left}" y1="{top}" x2="{left}" y2="{height-bottom}" stroke="black"/>\n'
            f'<polyline points="{polyline}" fill="none" stroke="#1f77b4" stroke-width="2"/>\n'
            f"{circles}\n"
            f'<text x="{width/2:.1f}" y="{height-15}" text-anchor="middle" font-family="sans-serif" font-size="14">{x_axis}</text>\n'
            f'<text x="18" y="{height/2:.1f}" transform="rotate(-90 18 {height/2:.1f})" text-anchor="middle" font-family="sans-serif" font-size="14">{metric}</text>\n'
            f'<text x="{left}" y="{top+14}" font-family="sans-serif" font-size="12">x=[{xmin:.4g},{xmax:.4g}] y=[{ymin:.4g},{ymax:.4g}]</text>\n'
            "</svg>\n"
        )
    return True


def safe_name(text: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", required=True, type=Path)
    parser.add_argument("--plot-dir", required=True, type=Path)
    parser.add_argument("--x-axis", default="PW_count", help="numeric x-axis column, e.g. PW_count or PW_cutoff_or_shell")
    parser.add_argument("--metric", action="append", default=[], help="metric column to plot; may be repeated")
    parser.add_argument("--include-bad", action="store_true", help="include rows with bad != F")
    args = parser.parse_args()

    rows = filter_rows(read_table(args.summary), args.include_bad)
    if not rows:
        raise SystemExit("no rows to plot after bad-row filtering")
    args.plot_dir.mkdir(parents=True, exist_ok=True)
    metrics = metric_columns(rows, args.metric or list(DEFAULT_METRICS))
    if not metrics:
        raise SystemExit("no plottable metric columns found")
    for metric in metrics:
        stem = f"{safe_name(args.x_axis)}__{safe_name(metric)}"
        tsv_path = args.plot_dir / f"{stem}.tsv"
        png_path = args.plot_dir / f"{stem}.png"
        svg_path = args.plot_dir / f"{stem}.svg"
        points = write_metric_tsv(tsv_path, args.x_axis, metric, rows)
        png_written = try_plot_png(png_path, args.x_axis, metric, points)
        svg_written = False if png_written else write_simple_svg(svg_path, args.x_axis, metric, points)
        print(
            f"metric={metric} points={len(points)} tsv={tsv_path} "
            f"png={png_path if png_written else 'not_written'} svg={svg_path if svg_written else 'not_written'}"
        )


if __name__ == "__main__":
    main()
