#!/bin/sh
set -eu
cp ../pseudo/H_rps.dat ./
# Producer is the freshly verified 427_H_pbeh40_rvv10_dc_gs test.
test -d ../427_H_pbeh40_rvv10_dc_gs/data_dcdft
cp -R ../427_H_pbeh40_rvv10_dc_gs/data_dcdft ./
